"""add payment_method to orders

Revision ID: 8e429c931936
Revises: ca8b7c9a703d
Create Date: 2026-06-13 12:59:44.598124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e429c931936'
down_revision: Union[str, None] = 'ca8b7c9a703d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('orders', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # Update existing rows to 'cod'
    op.execute("UPDATE orders SET payment_method = 'cod'")
    # Make it non-nullable
    op.alter_column('orders', 'payment_method', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
